# Generated by Django 5.2.3 on 2025-06-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='belt',
            name='color',
            field=models.CharField(default='#B48A3A', help_text='Hex color code for the belt (e.g., #FFFFFF).', max_length=7),
        ),
        migrations.AddField(
            model_name='belt',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color for text on the belt (e.g., #000000).', max_length=7),
        ),
    ]
