# Generated by Django 5.2.3 on 2025-06-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0002_belt_color_belt_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belt',
            name='text_color',
        ),
    ]
