# Generated by Django 5.2.3 on 2025-06-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0003_remove_belt_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='video_enabled',
            field=models.BooleanField(default=False, help_text='Show video player/placeholder on the technique page.'),
        ),
    ]
