# Generated by Django 5.2.3 on 2025-06-21 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0004_technique_video_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(help_text='Order in which groups appear on the dashboard.', unique=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='belt',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group this belt belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belts', to='belts.beltgroup'),
        ),
    ]
