# Generated by Django 5.2.3 on 2025-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0005_beltgroup_belt_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='beltgroup',
            name='color',
            field=models.CharField(default='#696969', help_text="Hex color code for the group's folder (e.g., #696969).", max_length=7),
        ),
    ]
