# Generated by Django 5.2.3 on 2025-07-13 15:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0006_beltgroup_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video File'), ('article', 'Article (Rich Text)'), ('link', 'External Link')], max_length=10)),
                ('file', models.FileField(blank=True, help_text='PDF or video file', null=True, upload_to='supplemental/')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='For articles (rich text)', null=True)),
                ('external_url', models.URLField(blank=True, help_text='For external links', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='supplemental_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplemental_materials', to='belts.belt')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
