# Generated by Django 5.2.3 on 2025-07-13 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0007_supplementalmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_global', models.BooleanField(default=False, help_text='True if published by teacher, False if student/private')),
                ('promotion_requested', models.BooleanField(default=False, help_text='Student requested promotion to global')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_global', 'name'],
                'unique_together': {('name', 'created_by', 'is_global')},
            },
        ),
        migrations.CreateModel(
            name='TechniqueTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_assignments', to='belts.tag')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='belts.technique')),
                ('user', models.ForeignKey(blank=True, help_text='Null for global assignment, set for student-specific', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('technique', 'tag', 'user')},
            },
        ),
    ]
